server:
  port: 369
  servlet:
    context-path: /e8
spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: true
    prefix: classpath:/resources/templates/
  mvc:
    favicon:
      enabled: true
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
debug: false
logging:
  config: classpath:logback-spring.xml